Repository OvertureMaps/schema, pull requests merged in 2024-04, with the labels that each got.

#157 Remove details of GERS ID structure from documentation
  docusaurus/docs/gers/gers.mdx
Labels: documentation, 2024-04-16-release

#154 add path road class
  examples/transportation/segment/road/road-path.yaml
  schema/transportation/segment.yaml
Labels: Transportation, schema, v1.0

#155 Adding titles / documentation update
  schema/buildings/defs.yaml
  schema/defs.yaml
Labels: documentation

#158 add reference docs for `divisions` and remove narrative docs from schema repo
  docusaurus/docs/gers/gers.mdx
  docusaurus/docs/gers/scenarios.mdx
  docusaurus/docs/gers/terminology.mdx
  docusaurus/docs/overview/feature-model/geojson.mdx
  docusaurus/docs/overview/feature-model/index.mdx
  docusaurus/docs/overview/feature-model/names.mdx
  docusaurus/docs/overview/feature-model/scoping-rules.mdx
  docusaurus/docs/overview/index.mdx
  docusaurus/docs/reference/admins/administrative-boundary.mdx
  docusaurus/docs/reference/admins/locality.mdx
  docusaurus/docs/reference/admins/locality_area.mdx
  docusaurus/docs/reference/base/infrastructure.mdx
  docusaurus/docs/reference/base/land.mdx
  docusaurus/docs/reference/base/land_use.mdx
  docusaurus/docs/reference/base/water.mdx
  docusaurus/docs/reference/buildings/building.mdx
  docusaurus/docs/reference/buildings/building_part.mdx
  docusaurus/docs/reference/divisions/boundary.mdx
  docusaurus/docs/reference/divisions/division.mdx
  docusaurus/docs/reference/divisions/division_area.mdx
  docusaurus/docs/reference/index.mdx
  docusaurus/docs/reference/places/place.mdx
  docusaurus/docs/reference/transportation/connector.mdx
  docusaurus/docs/reference/transportation/segment.mdx
  docusaurus/docs/themes/admins/admins.mdx
  docusaurus/docs/themes/base/index.mdx
  docusaurus/docs/themes/buildings/building.mdx
  docusaurus/docs/themes/places/place.mdx
  docusaurus/docs/themes/themes.mdx
  docusaurus/docs/themes/transportation/index.mdx
  docusaurus/docs/themes/transportation/roads.mdx
  docusaurus/docs/themes/transportation/shape-connectivity.mdx
  docusaurus/docs/themes/transportation/travel-modes.mdx
  docusaurus/sidebars.js
  docusaurus/src/components/shared-libs/yamlFileResolver.js
Labels: documentation, 2024-04-16-release

#172 Replace todo with link
  schema/places/place.yaml
Labels: Places
